name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main            # run on every push to main
  workflow_dispatch:     # allow manual "Run workflow"

permissions:
  contents: write        # needed to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web --release --base-href "/solar_decision_tree/"
        
      - name: Add 404 fallback
        run: cp build/web/index.html build/web/404.html

      - name: Publish to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
